apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
spec:
  channel: release-2.11
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # # schedule to infrastructure nodes:
  # config:
  #   nodeSelector:
  #     node-role.kubernetes.io/infra: ""
  #   tolerations:
  #   - key: node-role.kubernetes.io/infra
  #     effect: NoSchedule
  #     operator: Exists